CREATE TABLE IF NOT EXISTS products (
    id BIGINT PRIMARY KEY NOT NULL,
    product_id UNIQUE VARCHAR(200) NOT NULL,
    name VARCHAR(50) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    inventory INTEGER NOT NULL,
    available BOOLEAN NOT NULL,
    brand VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);